= Initialiser la Javadoc

//---------------------------------------------------------------

Soyez bien sûr d'avoir cloné le projet avec la commande *git clone [url du projet]*.

Connectez vous à l'aide de votre nom Githuh et Mdp

//---------------------------------------------------------------

Afin de générer automatiquement la javadoc de ce travail, nous avons tout d'abord compilé le fichier à l'aide des commandes suivantes :
*mvn clean*, qui permet de supprimer l'ancien code compilé
*mvn compile*, qui permet de créer le nouveau code compilé

Ensuite, afin de générer la javadoc, nous avons utilisé la commande suivante : 
*mvn javadoc*

Dans notre cas, nous avons précisément utilisé la commande "mvn javadoc:javadoc -f "c:\Users\Etudiant\Downloads\tp1-qualite\pom.xml" " qui nous permet de préciser quelle javadoc nous souhaitions générer.

Enfin, pour lancer le projet, nous avons utilisé les commandes :
*mvn package*, suivi de
*java -jar target/tp_qualite-1.0.jar* nous permettant d'exécuter le jar créé par la première commande.

URL de mon partenaire sur GitLab : https://gitlab.com/RaphaLLamothe/tp1-qualite
